package resources

object DrawableResources {
    const val AVATAR_AI = "avatar_ai"
    const val EMPTY_STATE = "empty_state"
    const val IC_ARROW_BACK = "ic_arrow_back"
    const val IC_AVATAR_ANONYMOUS = "ic_avatar_anonymous"
    const val IC_AVATAR_EMAIL = "ic_avatar_email"
    const val IC_AVATAR_GOOGLE = "ic_avatar_google"
    const val IC_CHAT_ADD = "ic_chat_add"
    const val IC_CHAT = "ic_chat"
    const val IC_CHECKED_CHECK_BOX = "ic_checked_check_box"
    const val IC_COPY = "ic_copy"
    const val IC_DELETE = "ic_delete"
    const val IC_DRAG_HANDLE = "ic_drag_handle"
    const val IC_EDIT = "ic_edit"
    const val IC_EMPTY_CHECK_BOX = "ic_empty_check_box"
    const val IC_FLAG_EN = "ic_flag_en"
    const val IC_FLAG_RU = "ic_flag_ru"
    const val IC_FLAG_UA = "ic_flag_ua"
    const val IC_LOGO_GOOGLE = "ic_logo_google"
    const val IC_MESSAGE_SEND = "ic_message_send"
    const val IC_NAVIGATION = "ic_navigation"
    const val IC_SETTINGS_ACCOUNT = "ic_settings_account"
    const val IC_SETTINGS_CHAT = "ic_settings_chat"
    const val IC_SETTINGS_FEEDBACK = "ic_settings_feedback"
    const val IC_SETTINGS_LANGUAGE = "ic_settings_language"
    const val IC_SETTINGS_PRIVACY = "ic_settings_privacy"
    const val IC_SETTINGS_THEME = "ic_settings_theme"
    const val IC_SETTINGS = "ic_settings"
    const val IC_SHARE = "ic_share"
    const val IC_TAB_FOUR = "ic_tab_four"
    const val IC_TAB_ONE = "ic_tab_one"
    const val IC_TAB_THREE = "ic_tab_three"
    const val IC_TAB_TWO = "ic_tab_two"
    const val IC_TOGGLE_PASSWORD_DISABLED = "ic_toggle_password_disabled"
    const val IC_TOGGLE_PASSWORD_ENABLED = "ic_toggle_password_enabled"
    const val ONBOARDING_INTRO = "onboarding_intro"

}